<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Thank you! See you soon!' => 'Спасибо! До скорого!',
  '2-3-hours game' => '2-3 часовая игра',
  'A tool to assess candidates and newcomers' => 'Отличный инструмент для оценки кандидатов и новых сотрудников',
  'Back to top' => 'Вверх страницы',
  'Based on best working practices' => 'Основан на лучшей управленческой практике',
  'Based on mathematical methods not just feelings' => 'Использует математические методы анализа<br />поведения, а не субъективные ощущения ',
  'Can be used by an unlimited number of applicants in any part of the world' => 'Позволяет тестировать любое количество людей в любой точке мира ',
  'Coming soon' => 'Скоро',
  'Easiest' => 'Самый простой',
  'Email - {email} has been already added before!' => 'Адрес - {email} уже был добавлен!',
  'Email {email} has been successfully added!' => 'Адрес{email}  успешно добавлен! ',
  'Enter your email address' => 'Введите ваш email',
  'Focused on key skills' => 'Оценивает ключевые для бизнеса навыки',
  'Invalid email - \'{email}\'!' => 'Невалидный email - \'{email}\'!',
  'Live tasks and decision-making situations' => 'Реальные задачи и ситуации, требующие принятия решений',
  'Most Reliable' => 'Самый надежный',
  'No hard-, soft- or any-ware required! ! Just make sure you are online' => 'Не требует затрат на софт, оборудование или помещения! Просто убедитесь, что вы онлайн.',
  'No proper response from server. Please try again later.' => 'Неправильный ответ от сервера. Попробуйте чуть посже ещё раз.',
  'No response from server. Please try again later.' => 'Не ответа от сервера. Попробуйте чуть посже ещё раз.',
  'Our Clients' => 'Наши клиенты',
  'Please enter a valid email address' => 'Пожалуйста, введите валидный емейл',
  'Results can be obtained and used immediately' => 'Моментально предоставляет готовые для использования результаты оценки',
  'Saves your time' => 'Экономит время',
  'Simulation aimed at testing manager’s skills' => 'Деловая симуляция, позволяющая оценить управленческие навыки',
  'Skiliks - game the skills' => 'Skiliks - играй навыками',
  'The easiest &amp; most reliable way to discover your people management skills!' => 'Самый простой и надежный способ проверить навыки менеджеров!',
  'Uses real work environment, tasks and decision making situations' => 'Максимально приближен к реальному деловому окружению, задачам и ситуациям',
  'Русский' => 'English',
  'Home' => 'Главная',
  'About' => 'О нас',
  'Product' => 'О продукте',
  'en' => 'ru',
  'Notify me' => 'Сообщить о запуске',
);
