<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Thank you! See you soon!' => 'Спасибо! До скорого!',
  '2-3-hours game' => '2-3 часовая игра',
  'A tool to assess candidates and newcomers' => 'Отличный инструмент для оценки кандидатов и новых сотрудников',
  'Back to top' => 'Наверх',
  'Based on best working practices' => 'Основан на лучшей управленческой практике',
  'Based on mathematical methods not just feelings' => 'Использует математические методы анализа<br />поведения, а не субъективные ощущения ',
  'Can be used by an unlimited number of applicants in any part of the world' => 'Позволяет тестировать любое количество людей в любой точке мира ',
  'Coming soon' => 'Скоро запуск',
  'Easiest' => 'Самый простой',
  'Email - {email} has been already added before!' => 'Адрес - {email} уже был добавлен!',
  'Email {email} has been successfully added!' => 'Адрес{email}  успешно добавлен! ',
  'Enter your email address' => 'Введите ваш email',
  'Focused on key skills' => 'Оценивает ключевые для бизнеса навыки',
  'Invalid email - \'{email}\'!' => 'Невалидный email - \'{email}\'!',
  'Live tasks and decision-making situations' => 'Реальные задачи и ситуации, требующие принятия решений',
  'Most Reliable' => 'Самый надежный',
  'No hard-, soft- or any-ware required! ! Just make sure you are online' => 'Не требует затрат на софт, оборудование или помещения! Просто убедитесь, что вы онлайн.',
  'No proper response from server. Please try again later.' => 'Неправильный ответ от сервера. Попробуйте чуть позже ещё раз.',
  'No response from server. Please try again later.' => 'Не ответа от сервера. Попробуйте чуть посже ещё раз.',
  'Our Clients' => 'Наши клиенты',
  'Please enter a valid email address' => 'Пожалуйста, введите валидный емейл',
  'Results can be obtained and used immediately' => 'Моментально предоставляет готовые для использования результаты оценки',
  'Saves your time' => 'Экономит время',
  'Simulation aimed at testing manager’s skills' => 'Деловая симуляция, позволяющая оценить управленческие навыки',
  'Skiliks - game the skills' => 'Skiliks - играй навыками',
  'The easiest &amp; most reliable way to discover your people management skills!' => 'Самый простой и надежный способ проверить навыки менеджеров!',
  'Uses real work environment, tasks and decision<br />making situations' => 'Максимально приближен к реальному деловому окружению, задачам и ситуациям',
  'Русский' => 'English',
  'Home' => 'Главная',
  'About' => 'О нас',
  'Product' => 'О продукте',
  'en' => 'ru',
  'ru' => 'en',
  'Notify me' => 'Сообщить о запуске',
  'About the Product' => 'О продукте',
  'We have created on-line business simulation to discover manager’s skills.' => 'Мы создали онлайн бизнес симуляцию, чтобы вы могли оценить навыки менеджера',
  'Assessor needs no more than 5 minutes to appoint the assessment session and get the results. Detailed and comprehensive report on productivity, demonsTated managerial skills and professional qualities will be provided for each assessed candidate.' => 'Вам потребуется не более пяти минут, чтобы отправить приглашение и получить результаты. По каждому кандидату вам будет предоставлен исчерпывающий отчет орезультативности,  проявленных навыках и качествах менеджера.',
  'Applicant needs 2-3 hours to get  through the exciting gameplay allowing a deep immersion into real working environment with managerial tasks and decision-making situations.' => 'Кандидату потребуется 2-3 часа, чтобы пройти увлекательную игру с глубоким погружением в реальную рабочую среду с менеджерскими задачами и ситуациями принятия управленческих решений.',
  'Assessment outcome of a particular person can be compared with the outcomes of other people with different backgrounds, geographies, etc. This option is available for either assessors or applicants.' => 'Вы сможете сравнить между собой кандидатов с самым разнообразным опытом, из разных отраслей или регионов, по одинаковой шкале оценки навыков, качеств и достигнутых результатов.',
  'More Information' => 'Подробнее',
  'Our simulation is the easiest and most reliable way to discover your people management skills:' => 'Наша симуляция – самый простой и надежный способ проверить навыки менеджеров',
  'Easiest' => 'Самый простой',
  'Saves your time' => 'Экономит время',
  'Add up the number of hours you waste on the futile  interviews. Use these hours on your first priority project!' => 'Суммируйте все часы, потраченные на предварительные интервью с кандидатами…Используйте эти часы на задачи первого приоритета.',
  'Two clicks to start the process and get the necessary assessment.' => 'Только два клика отделяют вас от старта процесса оценки.',
  'Unlimited number of applicants in any part of the world.' => 'Позволяет тестировать любое количество людей в любой точке мира',
  'No limits! Use the simulation for managers from anywhere in the world. Assess as many people as you need.' => 'Никаких ограничений! Используйте симуляцию для оценки менеджеров в любой точке мира. Оценивайте столько людей, сколько вам необходимо!',
  'No hard-, soft- or any-ware required! Just make  sure you and your managers are on line!' => 'Не требует затрат на софт, оборудование или помещения! Просто убедитесь, что вы онлайн.',
  '<strong>NO NEED</strong> to  buy computers' => '<strong>НЕ нужно</strong> покупать дополнительные компьютеры.',
  '<strong>NO NEED</strong> to buy/distribute/integrate any soft' => '<strong>НЕ нужно</strong> покупать/устанавливать/интегрировать новое программное обеспечение',
  '<strong>NO NEED</strong> to lease additional office space' => '<strong>НЕ нужно</strong> расширять офис и выделять специальные места для тестирования',
  'Results can be used immediately' => 'Моментально предоставляет готовые для использования результаты оценки',
  '<strong>NO NEED</strong> to call experts to interpret the results! Just open your Skiliks Office and use the managers’ assessment data to make the decision!' => 'Не требуются эксперты для интерпретации результатов! Просто зайдите в ваш офис на skiliks.com и используйте информацию для принятия решения.',
  'Focused on the skills' => 'Оценивает ключевые для бизнеса навыки',
  'We focus the simulation on measuring  real managerial skills – their ability to bring value from the first working day. Skill itself is the mastered capacity to carry out pre-determined results with minimum resources.' => 'Навык – управляемая способность человека приносить конкретные результаты, затрачивая минимум ресурсов. Мы настроили симуляцию на оценку только ключевых навыков менеджера – его способность добавлять ценность с первого дня работы.',
  'Based on best working practices' => 'Основан на лучшей управленческой практике',
  'We developed the assessment based on the selection of crucial practical skills that define manager’s performance with detailed analysis of how these skills become apparent in behaviour' => 'Мы создали систему оценки на основе самых важныхпрактических навыков, непосредственно влияющих на эффективность менеджера, его способность создавать результаты для компании. Мы провели детальный анализ, как именно каждый навык проявляется в поведении.',
  'We are continuously up-grading managerial skills profile' => 'Мы не прекращаем совершенствовать как набор управленческих навыков, так и поведений, его раскрывающих.',
  'Uses real work environment, tasks and decision making situations' => 'Максимально приближен к реальному деловому окружению, задачам и ситуациям',
  'In the simulation we have replicated the manager’s everyday life - familiar tasks, situations, interfaces and office environment. It helps manager to be himself and demonstrate his best results.' => 'Мы постарались воссоздать атмосферу каждодневной жизни среднего менеджера: знакомые задачи, ситуации, интерфейсы и офисноеокружение. Все это помогает менеджеру оставаться собой и демонстрировать лучшие качества.',
  'Each skill is assessed in many instances throughout the simulation forming valid outcome. Just imagine how many days you need in order to do it in real life!' => 'Каждый навык тестируется многократно, в среднем около 10 проявлений, таким образом формируя достоверную итоговую оценку. Просто представьте сколько дней надо провести вместе с менеджером, чтобы сделать оценку столь же обоснованной!',
  'We collect and analyse the data of hundreds of participants to manage the simulation.' => 'Мы собираем и анализируем данные сотен участников, чтобы  корректно настроить симуляцию.',
  'We give you the possibility to compare candidates using clear quantitative criteria.' => 'Наш инструментарийдаетчеткие количественные критерии для оценки и сравнения кандидатов.',
);
