---
abstract: 'Multiplayer SocialCalc Server with WebSocket'
author:
  - '唐鳳 <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: cpal
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SocialCalc-Multiplayer
no_index:
  directory:
    - inc
    - socialcalc
requires:
  File::ShareDir: 0
  Fliggy: 0
  JSON: 0
  Protocol::WebSocket: 0
  Try::Tiny: 0
  perl: 5.8.1
resources:
  repository: http://github.com/audreyt/socialcalc
version: 20110626
